### ISSUE TITLE
加入“复制到剪贴板”按钮

### ISSUE THREAD

**Issue by xianfeng1128** [kqakqakqa/utf-block-sign-art#2]
以下为修改后的rendersign功能
```
    function renderSigns(signs, container) {
    container.innerHTML = "";
    signs.forEach((sign, index) => {
        let signElement = document.createElement("div");
        signElement.className = "sign";
        let signText = "";

        sign.forEach(signLineText => {
            let signLineElement = document.createElement("pre");
            signLineElement.className = "signLine";
            signLineElement.innerText = signLineText;
            signElement.appendChild(signLineElement);
            signText += signLineText + "\n";
        });

        let copyButton = document.createElement("button");
        copyButton.innerText = "复制到剪贴板";
        copyButton.onclick = function() {
            navigator.clipboard.writeText(signText).then(() => {
                alert("复制成功！");
            }).catch(err => {
                alert("复制失败: " + err);
            });
        };

        signElement.appendChild(copyButton);
        container.appendChild(signElement);
    });
}
```

**Comment by xianfeng1128** [comment]
伟大的工作，使我的城市旋转。
复制时选中略有艰难，故做此修改，望采纳

**Comment by kqakqakqa** [comment]
> 伟大的工作，使我的城市旋转。 复制时选中略有艰难，故做此修改，望采纳

看了这段代码，是给每个标志牌提供一个复制按钮？可能需要改一下逻辑，直接给每一行提供一个按钮，或者所有的标志牌只提供一个复制按钮

**Comment by xianfeng1128** [comment]
您好，感谢您的回应，因为基岩版是可以整个粘贴上去的，但是整个复制有些困难，所以我添加了按钮。
JAVA版逐行粘贴时我认为可以直接单击选中行随后复制粘贴即可。

**Comment by xianfeng1128** [comment]
如果可以添加一段解释性文本，说明JAVA版需逐行粘贴，基岩版则可使用按钮整个粘贴呢

**Comment by kqakqakqa** [comment]
> 以下为修改后的rendersign功能
> 
> ```
>     function renderSigns(signs, container) {
>     container.innerHTML = "";
>     signs.forEach((sign, index) => {
>         let signElement = document.createElement("div");
>         signElement.className = "sign";
>         let signText = "";
> 
>         sign.forEach(signLineText => {
>             let signLineElement = document.createElement("pre");
>             signLineElement.className = "signLine";
>             signLineElement.innerText = signLineText;
>             signElement.appendChild(signLineElement);
>             signText += signLineText + "\n";
>         });
> 
>         let copyButton = document.createElement("button");
>         copyButton.innerText = "复制到剪贴板";
>         copyButton.onclick = function() {
>             navigator.clipboard.writeText(signText).then(() => {
>                 alert("复制成功！");
>             }).catch(err => {
>                 alert("复制失败: " + err);
>             });
>         };
> 
>         signElement.appendChild(copyButton);
>         container.appendChild(signElement);
>     });
> }
> ```

可以提个pr吗

**Comment by xianfeng1128** [comment]
ok ha
[https://github.com/kqakqakqa/utf-block-sign-art/pull/3](url)
